//
//  ScenarioBrain.swift
//  On The Spot
//
//  Created by Carson Clark on 2023-12-26.
//

import Foundation

struct ScenarioBrain {
    let scenarioArray =  [
        Scenario(question: "Your partner is out of town and an ex asks to meet up for drinks. Do you take them up on their offer?", previouslyDisplayed: false),
        Scenario(question: "While swiping on Bumble, you see a coworker's significant other. Do you notify your colleague?", previouslyDisplayed: false),
        Scenario(question: "You match with an attractive person that your best friend has a massive crush on. Do you unmatch?", previouslyDisplayed: false),
        Scenario(question: "You are not physically ill, but emotionally, you're exhausted. Do you call in sick to work?", previouslyDisplayed: false),
        Scenario(question: "When cleaning up, you find your teenager's journal. Do you read it?", previouslyDisplayed: false),
        Scenario(question: "You're unemployed and enjoying the freedom. To collect unemployment insurance, you are expected to look for a job. Do you take the money if you're not?", previouslyDisplayed: false),
        Scenario(question: "Your electric scooter was stolen. You are shown a similar one that is not yours at the police station. Do you claim it?", previouslyDisplayed: false),
        Scenario(question: "Your company offers you a $3,000 annual bonus. You have a new job lined up in January, do you accept the bonus right before leaving?", previouslyDisplayed: false),
        Scenario(question: "You match with a person who is obviously much more interested in you then you are them. Do you invite them over when you are lonely or do you express your true feelings so as to not lead them on?", previouslyDisplayed: false),
        Scenario(question: "You are waiting at a redlight at 2 a.m. There is nobody around, do you run the light?", previouslyDisplayed: false),
        Scenario(question: "You are eating at a fast food establishment when you notice a cook drop a bun and then pick it and put it in a takeout bag. Do you voice your concern?", previouslyDisplayed: false),
        Scenario(question: "You apply for a job as a junior software developer. The company you're applying for gives you a take-home coding challenge, do you use chatGPT to complete it?", previouslyDisplayed: false),
        Scenario(question: "You are selling an item on Facebook Marketplace. Someone reaches out saying they'd like to pick it up today. Another person reaches out after saying they can pick up at the same time, and will give you $100 more. Do you take their offer?", previouslyDisplayed: false),
        Scenario(question: "The person in front of you drops a $100 bill without noticing. Do you inform them?", previouslyDisplayed: false),
        Scenario(question: "You are at a party and a friend offers you pill and claims it will help you relax. Do you try it once?", previouslyDisplayed: false),
        Scenario(question: "While laying next to your partner in bed watching TikTok you come across a stunning influencer wearing very little clothing. Do you watch the clip?", previouslyDisplayed: false),
        Scenario(question: "You are at a party and you spill beer on the hosts Xbox. Do you tell them?", previouslyDisplayed: false),
        Scenario(question: "You are in college with a paper due this Friday. You are enrolled in 5 other courses and are tight on time. Do you use ChatGPT to complete the assignment?", previouslyDisplayed: false),
        Scenario(question: "Your partner has put on some extra weight. Do you bring it up kindly or leave it alone?", previouslyDisplayed: false),
        Scenario(question: "While downtown during a riot, you notice people looting near-by establishments. Do you join in?", previouslyDisplayed: false),
        Scenario(question: "You are about to meet your S/O's parents. They are highly educated and a tad pretentious. Do you put on an act to sound more intellectual than you really are?", previouslyDisplayed: false),
        Scenario(question: "You accept a date with a nice person when an even more attractive prospect becomes available. Do you cancel the first date?", previouslyDisplayed: false),
        Scenario(question: "While out of town for work, you had a one night stand with someone you met at a bar. Do you tell your S/O?", previouslyDisplayed: false),
        Scenario(question: "You witness a friend cheating on a test. Would you report them to the Professor?", previouslyDisplayed: false),
        Scenario(question: "You accidentally damage someone's car in a parking lot. Do you leave a note with your contact information?", previouslyDisplayed: false),
        Scenario(question: "A close family member asks for assistance with covering for a hit and run. Nobody was killed, but somebody was injured and taken to the hospital. Do you turn them in?", previouslyDisplayed: false),
        Scenario(question: "After looking for work for 6 months, you get a good offer from a large tabacco maker, which is not in your field of interest. Do you accept it?", previouslyDisplayed: false),
        Scenario(question: "It is Black Friday and the parking lot is busy. You would like to run in and grab the latest Xbox. There is a spot open for curbside pickup that is right near the door. Do you park there?", previouslyDisplayed: false),
        Scenario(question: "A close friend is interviewing for a job with your employer. They ask for a list of interview questions. Do you provide it?", previouslyDisplayed: false),
        Scenario(question: "Your employer wants you to return to office despite the fact that your job can be done fully remote. Do you return to the office?", previouslyDisplayed: false),
        Scenario(question: "You suspect your uber driver to be intoxicated. Do you report them?", previouslyDisplayed: false),
        Scenario(question: "Your partner is out of town and you decide to go dancing with some friends. While dancing, someone is grinding up on you and is showing a large amount of interest. Do you continue to dance with them?", previouslyDisplayed: false),
        Scenario(question: "A nice guy offers to buy you a drink at a bar. You feel no attraction towards him. Do you accept his offer?", previouslyDisplayed: false),
        Scenario(question: "Your son has expressed interest in studying computer science, however, his spatial reasoning and math skills are well below average. Do you encourage him regardless?", previouslyDisplayed: false),
        Scenario(question: "Your employer is making you pronouns mandatory in your email signautre. Do you oppose?", previouslyDisplayed: false),
        Scenario(question: "Your partner wants to bring a third party of the opposite sex into the bed room to spice things up. Do you agree?", previouslyDisplayed: false),
        Scenario(question: "You find an old positive covid test in your bathroom. Do you use it get a week off of work?", previouslyDisplayed: false),
        Scenario(question: "You are fresh out of a relationship and while out on the town you come across your ex's attractive best friend. She is flirting with you, do you flirt back?", previouslyDisplayed: false),
        Scenario(question: "Your friend leaves their vape at your house and you've been enjoying it. Do you offer to return it?", previouslyDisplayed: false),
        Scenario(question: "You learn that your partner has slept with far more people than you thought. Do you stay together?", previouslyDisplayed: false),
        Scenario(question: "During a meeting with your teacher, you notice an answer sheet on their desk. Do you take a picture when they're not looking?", previouslyDisplayed: false),
        Scenario(question: "Your employer is asking everyone in the department to stay late and tidy the staff room. It's 5pm on a Friday evening. Do you say that you're sick to get out of it?", previouslyDisplayed: false),
        Scenario(question: "You come across an exciting job listing on Indeed. The pay is exceptional, the schedule is flexible and you know that you are an ideal candidate. However, it requires a bachelor's degree, and you never went to college. Do you lie on your resume?", previouslyDisplayed: false),
        Scenario(question: "After surgery, your Dentist writes you a perscription for Dilaudid - a strong pain killer. Weeks go by and you have made a full recovery but you really miss the high. Do you lie to your Doctor in an effort to obtain more drugs?", previouslyDisplayed: false),
        Scenario(question: "You are a Computer Technician who assists mostly seniors. An old lady calls you weekly because she thinks she downloaded a virus. However, it's just a simple scam pop up. Do you continue to charge her for your time, or do you instruct her to close the window?", previouslyDisplayed: false),
        Scenario(question: "A coworker burps in your face and then says 'whoops, you might smell cherios in a moment'. Do you fake laugh or confront them on their rude behaviour?", previouslyDisplayed: false),
        Scenario(question: "You see your ex while clubbing. You are both drunk and grinding on the dance floor. They ask you to go back to their place, do you oblige?", previouslyDisplayed: false),
        Scenario(question: "You get a job offer that pays a generous 6-figure salary but you are not passionate about the work. Do you accept the offer or continue to look elsewhere?", previouslyDisplayed: false),
        Scenario(question: "Your best friend's little sister is always flirting with you. Do you flirt back or keep your distance out of respect?", previouslyDisplayed: false),
        Scenario(question: "Your childhood friend invites you to hang out while they're in town. You have a date lined up with an attractive prospect, but you rarely get to see your friend. Do you cancel the date to see your friend instead?", previouslyDisplayed: false),
        Scenario(question: "You intend on paying for dinner while our with your parenter and their parents. However, their parents racked up a massive bill that you can't really afford. Do you offer to pay anyway?", previouslyDisplayed: false),
        Scenario(question: "Your friend sets up a media server with access to virtually every TV show and movie imaginable. They send you a link so you can enjoy access too, but you know it was all obtained illegally. Do you care?", previouslyDisplayed: false),
        Scenario(question: "You inherit $300,000 from a loved one. Do you go to work the next day?", previouslyDisplayed: false),
        Scenario(question: "While online shopping you notice knock-off designer brands being sold for dirt cheap. They're essentially indistinguishable from the real thing, do you buy a few items?", previouslyDisplayed: false),
        Scenario(question: "Your partner wants to quit their day job to pursue music. They're not awful, but not amazing either. Do you encourage them?", previouslyDisplayed: false),
        Scenario(question: "An opportunity comes up to go on a free trip to Vegas with you and one other person. You have two siblings that wish to go, what do you do?", previouslyDisplayed: false),
        Scenario(question: "You are behind on your student loans and you need some quick cash. Do you sell feet pictures online?", previouslyDisplayed: false),
        Scenario(question: "You are on a first date with a person you have no interest in. While they are in the bathroom, an attactive person invites you over to their table. Do you remain seated?", previouslyDisplayed: false),
        Scenario(question: "Your coworker consistently takes credit for your ideas during team meetings. Do you confront them privately or address it with your supervisor?", previouslyDisplayed: false),
        Scenario(question: "You witness a group of teenagers vandalizing public property in your neighborhood. Do you intervene and try to stop them or report the incident to the authorities anonymously?", previouslyDisplayed: false),
        Scenario(question: "You discover that your partner has been secretly going through your phone and social media accounts. Do you confront them about the breach of privacy or change your passwords without mentioning it?", previouslyDisplayed: false),
        Scenario(question: "You receive an invitation to a wedding where you know both the bride and groom have cheated on each other in the past. Do you attend the wedding or decline the invitation?", previouslyDisplayed: false),
        Scenario(question: "You witness your neighbor leaving their pet alone in their backyard for extended periods without food or water. Do you confront them about their neglectful behavior or report them to animal services?", previouslyDisplayed: false),
        Scenario(question: "You find out that your favorite local restaurant has been serving expired food. Do you inform the health department about the violation or stop dining there without saying anything?", previouslyDisplayed: false),
        Scenario(question: "You receive a significant refund from a store due to a pricing error on their part. Do you keep the extra money or notify the store of the mistake?", previouslyDisplayed: false),
        Scenario(question: "You find out that your colleague has been spreading false rumors about another coworker to tarnish their reputation. Do you confront them about their unethical behavior?", previouslyDisplayed: false),
        Scenario(question: "You receive a job offer from a company you applied to months ago but no longer have any interest in working for. Do you decline the offer politely or accept it temporarily while continuing to search for better opportunities?", previouslyDisplayed: false),
        Scenario(question: "Your friend asks you to cover for them by lying to their significant other about their whereabouts. Do you agree to cover for them or refuse to lie on their behalf?", previouslyDisplayed: false),
        Scenario(question: "You witness a stranger harassing someone on public transportation. Do you intervene or stay out of it?", previouslyDisplayed: false),
        Scenario(question: "Your friend asks you to borrow a significant amount of money, but you have doubts about their ability to repay it. Do you lend them the money and risk damaging the friendship, or politely decline?", previouslyDisplayed: false),
        Scenario(question: "You discover that your partner has been keeping old love letters and mementos from past relationships hidden away. Do you confront them about it or respect their privacy and trust?", previouslyDisplayed: false),
        Scenario(question: "You find out that your child has been bullying other students at school. Do you confront them about their behavior and impose consequences or seek professional help to address the underlying issues?", previouslyDisplayed: false),
        Scenario(question: "Your boss asks you to manipulate financial records to hide company losses. Do you comply with their request and risk legal repercussions, or refuse to participate in unethical behavior?", previouslyDisplayed: false),
        Scenario(question: "Your partner expresses interest in opening a joint bank account, but you have concerns about their financial habits and trustworthiness. Do you agree to the joint account?", previouslyDisplayed: false),
        Scenario(question: "You witness a driver texting while driving recklessly on the highway. Do you report the driver to the authorities or ignore it?", previouslyDisplayed: false),
        Scenario(question: "You notice a coworker consistently arriving late to work and leaving early, while still claiming full hours. Do you bring it to the attention of management?", previouslyDisplayed: false),
        Scenario(question: "You discover an error in your favor on your monthly utility bill. Do you report the error to the company or keep quiet and enjoy the savings?", previouslyDisplayed: false),
    ]
}
